# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, overload

import dissect.cstruct as __cs__
from typing_extensions import TypeAlias

class _c_leveldb(__cs__.cstruct):
    LOG_BLOCK_SIZE: Literal[32768] = ...
    LOG_ENTRY_HEADER_SIZE: Literal[7] = ...
    LDB_MAGIC: Literal[15800726617472432983] = ...
    LDB_FOOTER_SIZE: Literal[48] = ...
    LDB_BLOCK_TRAILER_SIZE: Literal[5] = ...
    class varint(__cs__.ProtobufVarint): ...
    class varint64(__cs__.ProtobufVarint): ...
    class varint32(__cs__.ProtobufVarint32): ...

    class LogBlockType(__cs__.Enum):
        FULL = ...
        FIRST = ...
        MIDDLE = ...
        LAST = ...

    class LogBlockHeader(__cs__.Structure):
        crc32c: _c_leveldb.uint32
        size: _c_leveldb.uint16
        type: _c_leveldb.LogBlockType
        @overload
        def __init__(
            self,
            crc32c: _c_leveldb.uint32 | None = ...,
            size: _c_leveldb.uint16 | None = ...,
            type: _c_leveldb.LogBlockType | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class BatchHeader(__cs__.Structure):
        seq_num: _c_leveldb.uint64
        rec_count: _c_leveldb.uint32
        @overload
        def __init__(self, seq_num: _c_leveldb.uint64 | None = ..., rec_count: _c_leveldb.uint32 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class RecordState(__cs__.Enum):
        DELETED = ...
        LIVE = ...
        UNKNOWN = ...

    class Record(__cs__.Structure):
        state: _c_leveldb.RecordState
        key_len: _c_leveldb.varint
        key: __cs__.CharArray
        @overload
        def __init__(
            self,
            state: _c_leveldb.RecordState | None = ...,
            key_len: _c_leveldb.varint | None = ...,
            key: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class BlockHandle(__cs__.Structure):
        offset: _c_leveldb.varint
        length: _c_leveldb.varint
        @overload
        def __init__(self, offset: _c_leveldb.varint | None = ..., length: _c_leveldb.varint | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class BlockEntry(__cs__.Structure):
        shared_len: _c_leveldb.varint32
        non_shared_len: _c_leveldb.varint32
        value_len: _c_leveldb.varint32
        key: __cs__.CharArray
        value: __cs__.CharArray
        @overload
        def __init__(
            self,
            shared_len: _c_leveldb.varint32 | None = ...,
            non_shared_len: _c_leveldb.varint32 | None = ...,
            value_len: _c_leveldb.varint32 | None = ...,
            key: __cs__.CharArray | None = ...,
            value: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class CompressionType(__cs__.Enum):
        NONE = ...
        SNAPPY = ...

    class BlockTrailer(__cs__.Structure):
        compression: _c_leveldb.CompressionType
        crc32c: __cs__.CharArray
        @overload
        def __init__(
            self, compression: _c_leveldb.CompressionType | None = ..., crc32c: __cs__.CharArray | None = ...
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class LdbFooter(__cs__.Structure):
        meta_index_handle: _c_leveldb.BlockHandle
        index_handle: _c_leveldb.BlockHandle
        @overload
        def __init__(
            self,
            meta_index_handle: _c_leveldb.BlockHandle | None = ...,
            index_handle: _c_leveldb.BlockHandle | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_leveldb` is an instance of `_c_leveldb`, but then we can't use it in type hints
c_leveldb: TypeAlias = _c_leveldb
