# Generated by cstruct-stubgen
from typing import BinaryIO, overload

import dissect.cstruct as __cs__
from typing_extensions import TypeAlias

class _c_localstorage(__cs__.cstruct):
    class varint(__cs__.ProtobufVarint): ...
    class varint64(__cs__.ProtobufVarint): ...
    class varint32(__cs__.ProtobufVarint32): ...

    class LocalStorageAreaWriteMetaData(__cs__.Structure):
        lm_type: _c_localstorage.uint8
        last_modified: _c_localstorage.varint
        sb_type: _c_localstorage.uint8
        size_bytes: _c_localstorage.varint
        @overload
        def __init__(
            self,
            lm_type: _c_localstorage.uint8 | None = ...,
            last_modified: _c_localstorage.varint | None = ...,
            sb_type: _c_localstorage.uint8 | None = ...,
            size_bytes: _c_localstorage.varint | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class LocalStorageAreaAccessMetaData(__cs__.Structure):
        la_type: _c_localstorage.uint8
        last_accessed: _c_localstorage.varint
        @overload
        def __init__(
            self, la_type: _c_localstorage.uint8 | None = ..., last_accessed: _c_localstorage.varint | None = ...
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_localstorage` is an instance of `_c_localstorage`, but then we can't use it in type hints
c_localstorage: TypeAlias = _c_localstorage
